export const characterActions = {
  CHARACTERS_FETCH_START: "CHARACTERS_FETCH_START",
  CHARACTERS_FETCH_SUCCESS: "CHARACTER_FETCH_SUCCESS",
  CHARACTERS_FETCH_FAILURE: "CHARACTERS_FETCH_FAILURE",
  FETCH_CHARACTER_START: "FETCH_CHARACTER_START",
  FETCH_CHARACTER_SUCCESS: "FETCH_CHARACTER_SUCCESS",
  FETCH_CHARACTER_FAILURE: "FETCH_CHARACTER_FAILURE",
  SELECT_CHARACTER: "SELECT_CHARACTER",
  BACK_SELECT_CHARACTER: "BACK_SELECT_CHARACTER"
};

export const generalActions = {
  CLOSE_DRILL_DOWN: "CLOSE_DRILL_DOWN"
};

export const bookActions = {
  BOOKS_FETCH_START: "BOOKS_FETCH_START",
  BOOKS_FETCH_SUCCESS: "BOOKS_FETCH_SUCCESS",
  BOOKS_FETCH_FAILURE: "BOOKS_FETCH_FAILURE"
};

export const houseActions = {
  HOUSES_FETCH_START: "HOUSES_FETCH_START",
  HOUSES_FETCH_SUCCESS: "HOUSES_FETCH_SUCCESS",
  HOUSES_FETCH_FAILURE: "HOUSES_FETCH_FAILURE",
  SELECT_HOUSE: "SELECT_HOUSE",
  FETCH_HOUSE_START: "FETCH_HOUSE",
  FETCH_HOUSE_SUCCESS: "FETCH_HOUSE_SUCCESS",
  FETCH_HOUSE_FAILURE: "FETCH_HOUSE_FAILURE",
  BACK_SELECT_HOUSE: "BACK_SELECT_HOUSE"
};

