export const characterActions = {
  CHARACTERS_FETCH_START: "CHARACTERS_FETCH_START",
  CHARACTERS_FETCH_SUCCESS: "CHARACTER_FETCH_SUCCESS",
  CHARACTERS_FETCH_FAILURE: "CHARACTERS_FETCH_FAILURE"
};

export const bookActions = {
  BOOKS_FETCH_START: "BOOKS_FETCH_START",
  BOOKS_FETCH_SUCCESS: "BOOKS_FETCH_SUCCESS",
  BOOKS_FETCH_FAILURE: "BOOKS_FETCH_FAILURE"
}